#!/bin/bash

echo "Becoming ${GITLAB_USER_NAME} (${GITLAB_USER_LOGIN}) <${GITLAB_USER_EMAIL}>..."
git config --global user.name "${GITLAB_USER_NAME}"
git config --global user.email "${GITLAB_USER_EMAIL}"

#get version from DESCRIPTION file
VERSION=`cat DESCRIPTION | grep Version: | sed -E "s/Version:\\s+//g"`

#replace . with space so can split into an array
VERSION_BITS=(${VERSION//./ })

#get number parts and increase last one by 1
VNUM1=${VERSION_BITS[0]}
VNUM2=${VERSION_BITS[1]}
VNUM3=${VERSION_BITS[2]}
VNUM3=$((VNUM3+1))

#create new tag
NEW_TAG="$VNUM1.$VNUM2.$VNUM3"

echo "Updating $VERSION to $NEW_TAG"

#get current hash and see if it already has a tag
GIT_COMMIT=`git rev-parse HEAD`
NEEDS_TAG=`git describe --contains $GIT_COMMIT 2>/dev/null`


export DATE=$(date +"%Y-%m-%d")
sed "s|Version:.*|Version: ${NEW_TAG}|g" DESCRIPTION > DESCRIPTION_UP
sed "s|Date:.*|Date: ${DATE}|g" DESCRIPTION_UP > DESCRIPTION_UP_DATE

mv -f DESCRIPTION_UP_DATE DESCRIPTION
rm -rf DESCRIPTION_UP*
cat DESCRIPTION

git add DESCRIPTION
git commit -m "release: $NEW_TAG"

#only tag if no tag already
if [ -z "$NEEDS_TAG" ]; then
    git tag $NEW_TAG
    echo "Tagged with $NEW_TAG"
else
    echo "Already a tag on this commit"
fi

git push "https://${GITLAB_USER_LOGIN}:${CI_GIT_TOKEN}@${CI_REPOSITORY_URL#*@}" HEAD:master -o ci.skip
git push "https://${GITLAB_USER_LOGIN}:${CI_GIT_TOKEN}@${CI_REPOSITORY_URL#*@}" HEAD:master --tags
