# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hash_string_vector <- function(sv) {
    .Call('jsutils_hash_string_vector', PACKAGE = 'jsutils', sv)
}

inplace <- function(ls, newls) {
    .Call('jsutils_inplace', PACKAGE = 'jsutils', ls, newls)
}

triplet_prod <- function(i1, j1, x1, i2, j2, x2) {
    .Call('jsutils_triplet_prod', PACKAGE = 'jsutils', i1, j1, x1, i2, j2, x2)
}

triplet_prod_un <- function(i1, j1, x1, i2, j2, x2) {
    .Call('jsutils_triplet_prod_un', PACKAGE = 'jsutils', i1, j1, x1, i2, j2, x2)
}

partial_kronecker <- function(trl, trr, projl, projr, dim2) {
    .Call('jsutils_partial_kronecker', PACKAGE = 'jsutils', trl, trr, projl, projr, dim2)
}

